# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encrypted_package.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='encrypted_package.proto',
  package='demo',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x65ncrypted_package.proto\x12\x04\x64\x65mo\"8\n\x10\x45ncryptedPackage\x12\n\n\x02iv\x18\x14 \x02(\x0c\x12\x18\n\x10\x65ncryptedMessage\x18\x1e \x02(\x0c\"7\n\x0fPlaintextAndMAC\x12\x17\n\x0fpaddedPlaintext\x18\n \x02(\x0c\x12\x0b\n\x03mac\x18\x14 \x02(\x0c\"\'\n\x02IM\x12\x10\n\x08nickname\x18\x05 \x02(\t\x12\x0f\n\x07message\x18\n \x02(\t'
)




_ENCRYPTEDPACKAGE = _descriptor.Descriptor(
  name='EncryptedPackage',
  full_name='demo.EncryptedPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='iv', full_name='demo.EncryptedPackage.iv', index=0,
      number=20, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encryptedMessage', full_name='demo.EncryptedPackage.encryptedMessage', index=1,
      number=30, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=89,
)


_PLAINTEXTANDMAC = _descriptor.Descriptor(
  name='PlaintextAndMAC',
  full_name='demo.PlaintextAndMAC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='paddedPlaintext', full_name='demo.PlaintextAndMAC.paddedPlaintext', index=0,
      number=10, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mac', full_name='demo.PlaintextAndMAC.mac', index=1,
      number=20, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=146,
)


_IM = _descriptor.Descriptor(
  name='IM',
  full_name='demo.IM',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nickname', full_name='demo.IM.nickname', index=0,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='demo.IM.message', index=1,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=187,
)

DESCRIPTOR.message_types_by_name['EncryptedPackage'] = _ENCRYPTEDPACKAGE
DESCRIPTOR.message_types_by_name['PlaintextAndMAC'] = _PLAINTEXTANDMAC
DESCRIPTOR.message_types_by_name['IM'] = _IM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EncryptedPackage = _reflection.GeneratedProtocolMessageType('EncryptedPackage', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTEDPACKAGE,
  '__module__' : 'encrypted_package_pb2'
  # @@protoc_insertion_point(class_scope:demo.EncryptedPackage)
  })
_sym_db.RegisterMessage(EncryptedPackage)

PlaintextAndMAC = _reflection.GeneratedProtocolMessageType('PlaintextAndMAC', (_message.Message,), {
  'DESCRIPTOR' : _PLAINTEXTANDMAC,
  '__module__' : 'encrypted_package_pb2'
  # @@protoc_insertion_point(class_scope:demo.PlaintextAndMAC)
  })
_sym_db.RegisterMessage(PlaintextAndMAC)

IM = _reflection.GeneratedProtocolMessageType('IM', (_message.Message,), {
  'DESCRIPTOR' : _IM,
  '__module__' : 'encrypted_package_pb2'
  # @@protoc_insertion_point(class_scope:demo.IM)
  })
_sym_db.RegisterMessage(IM)


# @@protoc_insertion_point(module_scope)
